CursoGithub/django/django_project_learning/django_project_learning/urls.py
from django.contrib import admin
from django.urls import path, include

# importamos librerias para añadir a urlpatterns los media files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
]

# añadimos la función que incorpora los archivos a urlpatterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# esta función conecta, del archivo settings.py, la url de los archivos (MEDIA_URLS)
# con la raiz de almacenamiento (MEDIA_ROOT)

# funcion para incorporar archivos multimedia a urls en producción
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

CursoGithub/django/django_project_learning/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("login/", views.loginUser, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("register/", views.registerUser, name="register"),
    path("account/", views.userAccount, name="account"),

    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>', views.userProfile, name='user-profile'),
]

CursoGithub/django/django_project_learning/projects/models.py
from django.db import models
import uuid
from users.models import Profile

# from django.apps import apps

# Create your models here.


class Projects(models.Model):
    owner = models.ForeignKey(Profile, null= True, blank= True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null= True, blank= True)
    featured_image = models.ImageField(default='default_logo.png', null= True, blank= True)
    demo_link = models.CharField(max_length=2000, null= True, blank= True)
    source_link = models.CharField(max_length=2000, null= True, blank= True)

    # crear un atributo para relación 'Many to Many' con el objeto Tag
    tags = models.ManyToManyField('Tag', blank=True)

    # crear dos atributos que cuenten los votos y el ratio de positivos y negativos
    vote_total = models.IntegerField(default=0, null= True, blank= True)
    vote_ratio = models.IntegerField(default=0, null= True, blank= True)

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default= uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title


class Review(models.Model):
    """creamos una tupla de tuplas 'VOTE_TYPE' que será las opciones de elección para el atributo 'value' añadidas con parámetro 'choices'. """
    """el 1er valor de la tupla será el valor y el 2º el string que se muestra"""
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )

    # owner =
    project_fk = models.ForeignKey(Projects, on_delete=models.CASCADE)
    body = models.TextField(null= True, blank= True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default= uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default= uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name



"""--------------- TIMETRACKER -------------------"""


class TimeTracker(models.Model):
    project = models.OneToOneField(Projects, on_delete=models.CASCADE)
    total_hours = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return f'TimeTracker for {self.project.title}'

# # Importa 'Projects' en el nivel donde lo necesites, no en la parte superior del archivo.
# Projects = apps.get_model('projects', 'Projects')

CursoGithub/django/django_project_learning/users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# # importar Django Signal para notificaciones en acciones concretas: https://docs.djangoproject.com/en/4.1/ref/signals/

# from django.db.models.signals import post_save, post_delete

# # usar django signals con decorators (mejor)
# from django.dispatch import receiver

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200,null=True, blank=True)
    email= models.EmailField(max_length=500,null=True, blank=True)
    username = models.CharField(max_length=200,null=True, blank=True)
    location = models.CharField(max_length=200,null=True, blank=True)
    short_intro = models.CharField(max_length=200,null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profiles/', default='profiles/user_default.png')
    social_github = models.CharField(max_length=200,null=True, blank=True)
    social_linkedin = models.CharField(max_length=200,null=True, blank=True)
    social_twitter = models.CharField(max_length=200,null=True, blank=True)
    social_youtube = models.CharField(max_length=200,null=True, blank=True)
    social_website = models.CharField(max_length=200,null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default= uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)


class Skills(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200,null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default= uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

# # ------------------------------------- DJANGO SIGNALS ----------------------------------------------

# ## Función para enviar notif. con Django Signals después de actualizar un usuario
# # def profileUpdated(sender, instance, created, **kwargs):
# #     print('Profile saved')
# #     print('Instance: ', instance)
# #     print('Created: ', created)

# # post_save.connect(profileUpdated, sender=Profile) 
# # -> comentamos después de prueba inicial para hacerlo con decorators


# ## Función para enviar notif. con Django Signals después de actualizar un usuario
# # def deleteUser(sender, instance, **kwargs):
# #     print('Deleting user...')
# #     print('Instance: ', instance)

# # post_delete.connect(deleteUser, sender=Profile) -> comentamos después de prueba inicial para hacerlo con decorators


# ## Django signals con decorators

# # @receiver(post_save, sender=Profile)
# # def profileUpdated(sender, instance, created, **kwargs):
# #     print('Profile saved')
# #     print('Instance: ', instance)
# #     print('Created: ', created)

# @receiver(post_delete, sender=Profile)
# def deleteUser(sender, instance, **kwargs):
#     # lee el atributo user de Profile para hacer match con el usuario y eliminia el usuario también
#     user = instance.user
#     user.delete()

#     print('Deleting user...')
#     print('Instance: ', instance)


# ## usar Signals para crear un Profile cada vez que se dé de alta un usuario nuevo
# @receiver(post_save, sender=User)
# def createProfile(sender, instance, created, **kwargs):
#     # aquí la función lee si created es True, esto quiere decir que el user es nuevo
#     if created:
#         user = instance
#         profile = Profile.objects.create(
#             user = user,
#             username = user.username,
#             email = user.email,
#             name = user.first_name,
#             )
#         print(f"The user {user} has been created")

# # post_save.connect(createProfile, sender=User) 
         

CursoGithub/django/django_project_learning/users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {'first_name': 'Name', 'username': 'User name'}

    def __init__(self, *args, **kwargs):
        super(CustomRegistrationForm, self).__init__(*args, **kwargs)

        #--------- añadimos estilo a los campos del form desde el método con un dict que pasa la clase 
        # como key y el tipo 'input' como value para que identifique el campo como un input---------
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

        #----------- de este modo lo podemos hacer campo por campo -------------
        # self.fields['title'].widget.attrs.update({'class': 'input', 'placeholder': 'Add Title'})

CursoGithub/django/django_project_learning/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Profile
from .forms import CustomRegistrationForm

# Create your views here.

def loginUser(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        if User.objects.filter(username=request.POST['username']).exists():
            # try:
            #     user = User.object.get(username=username)
            # except:
            #     if username is None:
            #         messages.error(request, 'User does not exist')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('profiles')
            else:
                messages.error(request, "Username OR password is incorrect")
        else: messages.error(request, "Username doesn't exist")

    return render(request, 'users/login_register.html')


def logoutUser(request):
    logout(request)
    messages.info(request, 'User succesfully logged out')
    return redirect('login')


def registerUser(request):
    page = 'register'
    form = CustomRegistrationForm()

    if request.method == 'POST':  
        form = CustomRegistrationForm(request.POST)
        # antes de finalizar el registro, guardamos en una variable 'user' y lo pasamos por la función 'lower'
        # para evitar confusión y duplicidad de usernames por las mayúsculas  
        if form.is_valid(): 
            user = form.save(commit=False)
            user.username = user.username.lower()
            # ahora ya se puede generar el usuario
            user.save()

            messages.success(request, 'Account created successfully')

            login(request, user)
            return redirect('profiles')

        else:
            messages.error(request, 'An error occurred during registration')


    context = {'page': page, 'form': form}
    return render(request, 'users/login_register.html', context)




def profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles': profiles}

    return render(request, 'users/profiles.html', context)


def userProfile(request, pk):
    user_profile = Profile.objects.get(id=pk)

    # los modulos Profile y Skills están relacionados con la fk. Con 'skills_set' traemos el 
    # conjunto de skills relacionadas con el 'user_profile' seleccionado y las filtra, primero
    # por las que tienen descripcion (las excluye) y, segundo, por las que no (las incluye)
    top_skills = user_profile.skills_set.exclude(description__exact="")
    other_skills = user_profile.skills_set.filter(description="")

    context = {'profile': user_profile,'topSkills': top_skills, 'otherSkills': other_skills}

    return render(request, 'users/user_profile.html', context)


# con el decorador 'login_required' y añadiendo la variable 'profile' haciendo un request de la info del usuario
# no sería necesario pasar el parámetro 'pk' en la vista como hacemos en las otras (xej.: userProfile)
@login_required(login_url='login')
def userAccount(request):
    profile = request.user.profile
    context = {'profile': profile}

    return render(request, 'users/account.html', context)
    

CursoGithub/django/django_project_learning/users/templates/users/account.html
{% extends "main.html" %}
{% load static %}

{% block content %}

  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              <ul class="dev__social">
                <li>
                  <a title="Github" href="#" target="_blank"><i class="im im-github"></i></a>
                </li>
                <li>
                  <a title="Stackoverflow" href="#" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                <li>
                  <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                <li>
                  <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                <li>
                  <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                </li>
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="#"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
            {% for skill in profile.skills_set.all %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{skill}}</h4>
                <p>
                  {{skill.description|slice:"150"}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="#"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
            {% for project in profile.projects_set.all %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'project' project.id %}"><img src="{{project.featured_image.url}}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'project' project.id %}">{{project.title}}</a>
                <p>
                  {{project.description|slice:"200"}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
            {% comment %} <tr>
              <td class="settings__thumbnail">
                <a href="single-project.html"><img src="images/project-b.png" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="single-project.html">DevSearch Website UI Design</a>
                <p>
                  Consectetur adipisicing elit. Natus nam dolore aut sed vitae eos architecto unde tempore
                  exercitationem fugiat?...
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            <tr>
              <td class="settings__thumbnail">
                <a href="single-project.html"><img src="images/project-a.png" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="single-project.html">Portfolio Website Design</a>
                <p>
                  Consectetur adipisicing elit. Natus nam dolore aut sed vitae eos architecto unde tempore
                  exercitationem fugiat?...
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr> {% endcomment %}
          </table>
        </div>
      </div>
    </div>
  </main>

  {% endblock content %}

CursoGithub/django/django_project_learning/users/templates/users/login_register.html
{% extends 'main.html' %}
{% load static %}
{% block content %}




{% if page == 'register' %}

<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Account SignUp</h3>
      <p>Create a new developer account</p>
    </div>

    <form method="POST" action="{% url 'register' %}" class="form auth__form">
      {% csrf_token %}

      {% for field in form %}
      <!-- Input:Text -->
      <div class="form__field">
        <label for="formInput#text">{{field.label}} </label>
        {{field}}

        {% comment %} {% if field.help_text %}
          <small>{{field.help_text}}</small>
        {% endif %} {% endcomment %}

        {% for error in field.errors %}
          <p style="color: red;">{{error}}</p>
        {% endfor %}

      </div>

      {% endfor %}

      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
      </div>
    </form>
    <div class="auth__alternative">
      <p>Already have an Account?</p>
      <a href="{% url 'login' %}">Log In</a>
    </div>
  </div>
</div>

{% else %}
<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Account Login</h3>
        <p>Hello Developer, Welcome Back!</p>
      </div>

      <form action="{% url 'login' %}" method="POST" class="form auth__form">
        {% csrf_token %}
        <!-- Input:Username -->
        <div class="form__field">
          <label for="formInput#text">Username: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="username"
            placeholder="Enter your username..."
          />
        </div>

        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            placeholder="••••••••"
          />
        </div>
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
          <a href="forgetpassword.html">Forget Password?</a>
        </div>
      </form>
      <div class="auth__alternative">
        <p>Don’t have an Account?</p>
        <a href="{% url 'register' %}">Sign Up</a>
      </div>
    </div>
  </div>
{% endif %}

{% endblock content %}

CursoGithub/django/django_project_learning/users/templates/users/profiles.html
{% extends "main.html" %}

{% block content %}

<!-- Main Section -->
<main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>

    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
        
            {% for profile in profiles %}
            <div class="column card">
            <div class="dev">
              <a href="{% url 'user-profile' profile.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{profile.profile_image.url}}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{profile.name}}</h3>
                    <h5>{{profile.short_intro|slice:"60"}}</h5>
                  </div>
                </div>
                <p class="dev__info">{{profile.bio|slice:"150"}}</p>
                <div class="dev__skills">
                    {% for skill in profile.skills_set.all %}
                    <span class="tag tag--pill tag--main" >
                        <small>{{skill}}</small>
                    </span>
                    {% endfor %}
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>
  </main>
{% endblock content %}

CursoGithub/django/django_project_learning/users/templates/users/user_profile.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">  
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src= {{profile.profile_image.url}} />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">{{profile.location}}</p>
              <ul class="dev__social">

                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="icon-github"></i></a>
                </li>
                {% endif %}

                {% if profile.social_twitter %}
                <li>
                    <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}
                
                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}

                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">{{profile.bio}}</p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            {% for skill in topSkills %}
            <div class="devInfo__skills">
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill}}</h4>
                <p class="devSkill__info">{{skill.description}}</p>
              </div>
              {% endfor %}
              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                {% for skill in otherSkills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill}}</small>
                </span>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

            {% for project in profile.projects_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src={{project.featured_image.url}} alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="{% url 'user-profile' profile.id %}">By {{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                        Feedback 
                        <br>
                        ({{project.vote_total}} Vote{{ project.vote_total|pluralize:"s" }})
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main" >
                            {{tag}}
                        </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock content %}